### PR TITLE
Issue #704 resolved.

### PR DESCRIPTION
**Pull request by Ask-Subhasmita**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Ask-Subhasmita Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=706)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=706) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Ask-Subhasmita Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=706)!

**Comment by cppwfs** [comment]
The timestamp sample's  README.adoc needs to be updated, the master was updated earlier today. The file to be updated is located here: https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-samples/timestamp/README.adoc

**Comment by cppwfs** [comment]
Thank you for the contribution.  But it was handled by a PR that was submitted prior to this one  https://github.com/spring-cloud/spring-cloud-task/pull/705/commits.   
Please keep an eye out for new stories, we look forward to future contributions!

**Pull request closed without merging**
