### PR TITLE
Update appendix-task-repository-schema.adoc

### PR DESCRIPTION
**Pull request by Augilar**
Removed extra dashes which were creating extra coloumns

Screenshot (199)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Augilar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=731)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=731) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by Augilar** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by cppwfs** [comment]
On your side just accept the Contributor License Agreement.   On my side I'm working through the build issue.

**Comment by pivotal-issuemaster** [comment]
@Augilar Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=731)!

**Comment by Augilar** [comment]
I have signed the Contributor License Agreement but was it necessary as it was an obvious fix ?

**Comment by cppwfs** [comment]
Yep!  :-)   But now that you have done it, you won't have to do it again.   I will be merging your PR as soon as we resolve the other issue.   Thank you for your contribution.

**Comment by cppwfs** [comment]
LGTM Thank you for your contribution!

**Pull request merged**
