### PR TITLE
Upgrade to Dalston and Spring Boot 1.5.2

### LINKED ISSUE #286: Upgrade to Dalston and Spring Boot 1.5.2

### PR DESCRIPTION
**Pull request by trisberg**
Resolves #286

### CODE REVIEW

**Comment by cppwfs** [comment]
We are shooting for a M3 release for SCT Later this week so we can't use snapshot.

**Comment by trisberg** [comment]
Well, we have a chain of dependencies moving towards RC

Chelsea.RC1 -> Dalston.RC1 -> Deployer 1.2.0.M3 - all slated for early next week with the Deployer scheduled for Wednesday 3/15 together with SCDF 1.2.0.M3 which will need a new Task Milestone release

**Comment by cppwfs** [comment]
Found out we are not releasing Task this week.

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Rebased Merged

**Pull request closed without merging**
