### PR TITLE
Settings file is now present

### PR DESCRIPTION
**Pull request by cppwfs**
Used the same settings file from spring cloud stream

### CODE REVIEW

**Comment by trisberg** [comment]
Should we also add a <profile>  in the pom like we have in spring-cloud-stream? If we have the profile do we even need .settings.xml?

**Comment by mminella** [comment]
It's interesting that spring-cloud-stream has both a profile in the pom.xml and the .settings.xml.  And I thought that having repositories in poms that are published to central are a no-no: http://blog.sonatype.com/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/#.Vk-fp9-rSV4 ?

**Comment by cppwfs** [comment]
+1 on Michaels comments.

**Comment by mbogoevici** [comment]
The use of the profile prevents the repositories to show up in the published pom. Although it doesn't feel right. I would advise not to use the profile at all - we should probably get rid of it too ... 
 
http://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-stream-parent/1.0.0.M2/

**Pull request merged**
