### PR TITLE
Changed Java version from 7 to 8 in README

### PR DESCRIPTION
**Pull request by Arushi04**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Arushi04 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=705)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=705) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Arushi04 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=705)!

**Comment by cppwfs** [comment]
LGTM!   
Thank you for your contribution!

**Comment by cppwfs** [comment]
Whoops, I put the LGTM on it a bit early. The timestamp sample needs to be updated, the master was updated earlier today. The file to be updated is located here: https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-samples/timestamp/README.adoc

**Comment by cppwfs** [comment]
LGTM
Thank you for the contribution!

**Comment by cppwfs** [comment]
Rebased Merged

**Pull request closed without merging**
