### PR TITLE
Support DB2 on Mainframe as DB2ZOS

### LINKED ISSUE #303: Support DB2 on Mainframe as DB2ZOS
Looks like the database detection doesn't work for DB2ZOS

See: http://stackoverflow.com/questions/43380028/enabletask-annotation-does-not-support-db2-on-mainframe-on-db2zos

### PR DESCRIPTION
**Pull request by cppwfs**
resolves #303

Added support for DB2ZOS DatabaseType.
Added DB2AS400, DB2VSE, based on how Spring Batch implemeted DB2 identification via metadata.

Tested this against a local DB2.

### CODE REVIEW

**Comment by trisberg** [comment]
LGTM, let's wait and merge this until @crazynet can verify this now works on z/OS

**Comment by cppwfs** [comment]
Agreed!

**Comment by crazynet** [comment]
Apologies for bit late on responding to this.I will not be able to check now because I have been allocated to some other tasks instead of this.I will update you whenever I get a chance to test updated code.
Thanks.

**Comment by trisberg** [comment]
Thanks for the heads up. @cppwfs maybe we should just merge this now and @crazynet can open a new issue if there are additional problems.

**Comment by cppwfs** [comment]
Sounds like a plan!

**Comment by trisberg** [comment]
Squashed and merged as commit 6fad14ead731bb9eab09a15f5ada66d51e68e137

**Pull request closed without merging**
