### PR TITLE
Upgraded to Camden SR5

### LINKED ISSUE #276: Upgrade to Camden SR5
As a user, I want to be able to use the latest version of Spring Cloud.

### PR DESCRIPTION
**Pull request by mminella**
This commit upgrades Spring Cloud Task to Camden SR5 and makes the
required changes to do so.

Resolves #276

### CODE REVIEW

**Comment by cppwfs** [comment]
Do we need to bump up the dependencies parent?
        <parent>
                <artifactId>spring-cloud-dependencies-parent</artifactId>
                <groupId>org.springframework.cloud</groupId>
                <version>1.3.0.RELEASE</version>
         <relativePath />

**Comment by mminella** [comment]
Is that what's in Camden SR5?

**Comment by cppwfs** [comment]
Looks like it is 1.2.2.   Based on the following spring-cloud-dependences pom.
https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dependencies/Camden.SR5/spring-cloud-dependencies-Camden.SR5.pom

**Comment by cppwfs** [comment]
LGTM

**Pull request merged**
