### PR TITLE
Updated all Junit tests to 5.x

### PR DESCRIPTION
**Pull request by cppwfs**
resolves TASK-675

### CODE REVIEW

**Comment by mminella** [comment]
Unless I'm missing something, this PR only converts those in `spring-cloud-task-core` to JUnit 5. The other modules still use JUnit 4 (`spring-cloud-batch` for example).

**Comment by mminella** [comment]
When I run a full build, I get a test failure:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.136 s <<< FAILURE! - in io.spring.cloud.BatchEventsApplicationTests
[ERROR] testExecution  Time elapsed: 0.006 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at io.spring.cloud.BatchEventsApplicationTests.<clinit>(BatchEventsApplicationTests.java:39)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   BatchEventsApplicationTests.testExecution » ExceptionInInitializer
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Spring Cloud Task Build 2.3.0-SNAPSHOT:
[INFO]
[INFO] Spring Cloud Task Dependencies ..................... SUCCESS [  0.157 s]
[INFO] Spring Cloud Task Build ............................ SUCCESS [ 12.625 s]
[INFO] Spring Cloud Task Core ............................. SUCCESS [ 34.314 s]
[INFO] Spring Cloud Task Batch ............................ SUCCESS [01:10 min]
[INFO] Spring Cloud Task Stream ........................... SUCCESS [ 18.353 s]
[INFO] Spring Cloud Task Starter .......................... SUCCESS [  2.938 s]
[INFO] Timestamp Task ..................................... SUCCESS [  7.682 s]
[INFO] Batch Job Sample Application ....................... SUCCESS [  4.476 s]
[INFO] Task Sink Sample Application ....................... SUCCESS [  4.802 s]
[INFO] Task Processor Sample Application .................. SUCCESS [  4.961 s]
[INFO] Partitioned Batch Job .............................. SUCCESS [  1.598 s]
[INFO] Task Events ........................................ SUCCESS [  1.124 s]
[INFO] Batch Events Sample Application .................... FAILURE [  0.876 s]
[INFO] Spring Cloud Task JPA Sample Application ........... SKIPPED
[INFO] Spring Cloud Task Multiple DataSources Application . SKIPPED
[INFO] Spring Cloud Task Samples .......................... SKIPPED
[INFO] Spring Cloud Task Integration Tests ................ SKIPPED
[INFO] Spring Cloud Task Docs ............................. SKIPPED
[INFO] spring-cloud-starter-single-step-batch-job ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:45 min
[INFO] Finished at: 2020-07-01T11:42:50-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by cppwfs** [comment]
In this case make sure that your local docker instance is up an running, test containers requires it
.   I'll log an issue on the cryptic exception we got back from testcontainers.

**Comment by mminella** [comment]
Squashed and merged as 59c9adf0473bf4468e9ceb748c9e9d00f116a177

**Pull request closed without merging**
