### PR TITLE
Obtain the TaskRepositoryInitializer from the Default Configurer

### PR DESCRIPTION
**Pull request by mrbq**
Get the task database intialization datasource from the default task configurer. Making possible to have more than one datasource defined in the Spring context.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mrbq Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=452)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=452) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mrbq Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=452)!

**Comment by cppwfs** [comment]
I think the only thing missing from this PR is the tests that are the tests as shown in this PR.
https://github.com/spring-cloud/spring-cloud-task/commit/0915dc6dfec3ca463cdf5a5f24da1e58948e226c

Adding these tests should make this PR ready to go.

**Comment by cppwfs** [comment]
Added tests on merge.
Rebased, Squashed
Thank you for your contribution.

**Pull request closed without merging**
