### PR TITLE
Correct typo of closecontext.enable property in docs (Obvious Fix)

### PR DESCRIPTION
**Pull request by scbrown**
https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-core/src/main/java/org/springframework/cloud/task/listener/TaskLifecycleListener.java#L92

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@scbrown Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=216)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=216) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@scbrown Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=216)!

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Thank you for the contribution!

**Comment by scbrown** [comment]
@cppwfs thanks for Spring Cloud Task! Very cool stuff 👍

**Pull request merged**
