### PR TITLE
Adds DB2 support

### LINKED ISSUE #89: Add DB2 Server as supported databases
We should support the most commonly used databases, so this would mean we should add DB2 his would also be good for cloud deployments since Bluemix uses DB2

For popularity numbers see - http://db-engines.com/en/ranking_osvsc

### PR DESCRIPTION
**Pull request by tschuettel**
Provides the files and enum constants for Spring Cloud Task
to work with a DB2 database.

Resolves #89

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tschuettel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=228)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=228) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tschuettel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-task&pullRequestId=228)!

**Comment by trisberg** [comment]
LGTM, I'm adding the new ERROR_MESSAGE and EXTERNAL_EXECUTION_ID columns on merge

**Comment by trisberg** [comment]
Merged via commit c61a6e9c3520e6ef0c1fbd0b358c0e0206112a05

**Comment by trisberg** [comment]
Tested against DB2 Express-C using the following:

```
docker pull ibmcom/db2express-c:latest
docker run -it -p 50000:50000 -e DB2INST1_PASSWORD=datafl0w1 -e LICENSE=accept ibmcom/db2express-c:latest bash
su - db2inst1
db2start
db2 create db DATAFLOW
db2 connect to DATAFLOW
db2 "CREATE BUFFERPOOL DATAFLOWPOOL SIZE 2000 PAGESIZE 16K"
db2 "CREATE SYSTEM TEMPORARY TABLESPACE TEMPSPACE16 PAGESIZE 16K BUFFERPOOL DATAFLOWPOOL"
```

Download and install a JDBC driver, used this for Maven:

```
mvn install:install-file -DgroupId=com.ibm.db2.jcc -DartifactId=db2jcc4 -Dversion=4.19.66 -Dpackaging=jar -DgeneratePom=true -Dfile=/Users/trisberg/Developer/jdbc/db2/db2jcc4.jar
```

And then, built SCDF and a task app with this dependency added:

```
	<dependency>
		<groupId>com.ibm.db2.jcc</groupId>
		<artifactId>db2jcc4</artifactId>
		<version>4.19.66</version>
	</dependency>
```

Started local SCDF with:

```
java -jar spring-cloud-dataflow-server-local/target/spring-cloud-dataflow-server-local-1.1.0.BUILD-SNAPSHOT.jar --spring.datasource.url='jdbc:db2://127.0.0.1:50000/DATAFLOW:retrieveMessagesFromServerOnGetMessage=true;' --spring.datasource.username=DB2INST1 --spring.datasource.password=datafl0w1 --spring.datasource.driverClassName=com.ibm.db2.jcc.DB2Driver
```

**Pull request closed without merging**
