### PR TITLE
gh-235 Fix Sort Properties are ignored in JdbcTaskExecutionDao

### PR DESCRIPTION
**Pull request by ghillert**
- Add support for sorting similar to SCDF Core's `AbstractRdbmsKeyValueRepository`

Resolves https://github.com/spring-cloud/spring-cloud-task/issues/235

NOTE: `JdbcTaskExecutionDaoTests` lacks dedicated coverage for paging and sorting in general. Should those be rather covered in a separate issue ticket, in order to underline the implementation efforts?

### CODE REVIEW

**Comment by cppwfs** [comment]
LGTM except for the missing tests as we discussed.  I've added a basic set of tests, if you agree with them I can add them on merge.  
https://github.com/cppwfs/spring-cloud-task/blob/ghillert-gh-235/spring-cloud-task-core/src/test/java/org/springframework/cloud/task/repository/dao/JdbcTaskExecutionDaoTests.java#L154

**Comment by ghillert** [comment]
@cppwfs LTGM

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Added tests, squashed merged.

**Pull request closed without merging**
